modLoader="javafml"
loaderVersion="[35,)" 
license="All rights reserved"

[[mods]]
	modId="sunnyfood"
	version="${version}"
	displayName="Food Legend Mod"
	description='''
		a mod about very kind of foods
		you can use them to do many things
	'''


[[dependencies.sunnyfood]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sunnyfood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5)"
    ordering="NONE"
    side="BOTH"
